services:
  mysql-prd:
    image: mysql:${MYSQL_VERSION}
    container_name: mysql-hml-prd
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${PRD_MYSQL_ROOT_PASSWORD}
    ports:
      - "${PRD_MYSQL_PORT}:3306"
    volumes:
      - ../../data/prd:/var/lib/mysql
      - ./my.cnf:/etc/mysql/conf.d/custom.cnf
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "--silent"]
      interval: 5s
      timeout: 5s
      retries: 12
      start_period: 30s
